242: Fixed bug with filters in experiments
open-genes/open-genes-frontend pull request #250
Opened 2022-12-08 19:07 UTC by egervan

Fixed bug with filters that contains number value.
Also fixed bug with clearing filter that exists but contains null value

2022-12-11 02:26 UTC, const8ine requested changes
Оставил только совсем небольшой коммент по роуту

2022-12-11 02:26 UTC, const8ine commented on src/app/components/header/header.component.html
> -             [routerLink]="'/experiments'"
Вот тут надо оставить старый роут потому что он используется в научной статье, которую мы подали. Можно конечно сделать редирект, но лучше оставить как было

2022-12-11 02:26 UTC, const8ine commented on src/app/app-routing.ts
> +    path: 'studies',
Вот тут надо оставить старый роут потому что он используется в научной статье, которую мы подали. Можно конечно сделать редирект, но лучше оставить как было

2022-12-11 11:37 UTC, egervan commented on src/app/components/header/header.component.html
> -             [routerLink]="'/experiments'"
ok, в burger-menu тоже верну соответственно

2022-12-17 00:15 UTC, const8ine commented
PR is already merged https://github.com/open-genes/open-genes-frontend/commit/f30ffbf0674bd23b4a70a2e7d62de104f5607b29

2022-12-17 00:15 UTC, closed without merging